TotalSmartPortal/TotalPortal/Areas/Productions/ViewModels/ProductionOrderViewModel.cs
using System;
using System.Web.Mvc;
using System.Collections.Generic;

using TotalBase.Enums;
using TotalDTO.Productions;
using TotalPortal.Builders;
using TotalPortal.ViewModels.Helpers;
using TotalPortal.Areas.Commons.ViewModels.Helpers;

namespace TotalPortal.Areas.Productions.ViewModels
{
    public class ProductionOrderViewModel : ProductionOrderDTO, IViewDetailViewModel<ProductionOrderDetailDTO>, IPreparedPersonDropDownViewModel, IApproverDropDownViewModel, IA01SimpleViewModel
    {
        public IEnumerable<SelectListItem> AspNetUserSelectList { get; set; }
    }

}

TotalSmartPortal/TotalPortal/ViewModels/Helpers/PrintViewModel.cs
namespace TotalPortal.ViewModels.Helpers
{
    public class PrintViewModel
    {
        public int? Id { get; set; }
        public int? DetailID { get; set; }

        public int? FilterID { get; set; }

        public int LocationID { get; set; }

        public string ServerName { get { return "DATA-SERVER"; } }
        public string CatalogName { get { return "TotalSmartPortal"; } }

        public string ReportFolder { get { return "TotalSmartPortal"; } }
        public string ReportPath { get; set; }

        public int PrintOptionID { get; set; }
    }
}

TotalSmartPortal/TotalPortal/ViewModels/Helpers/VoidDetailViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

using TotalDTO.Commons;

namespace TotalPortal.ViewModels.Helpers
{
    public class VoidDetailViewModel
    {
        public int ID { get; set; }
        public int DetailID { get; set; }
        public bool InActivePartial { get; set; }

        public Nullable<int> VoidTypeID { get { return (this.VoidType != null ? this.VoidType.VoidTypeID : null); } }
        [UIHint("AutoCompletes/VoidType")]
        public VoidTypeBaseDTO VoidType { get; set; }

        public VoidDetailViewModel()
        {
            this.VoidType = new VoidTypeBaseDTO();
        }

    }
}

TotalSmartPortal/TotalPortal/Areas/Productions/Controllers/ProductionOrdersController.cs
using System.Net;
using System.Web.Mvc;
using System.Text;

using RequireJsNet;

using TotalBase.Enums;
using TotalDTO.Productions;
using TotalModel.Models;

using TotalCore.Services.Productions;

using TotalPortal.Controllers;
using TotalPortal.Areas.Productions.ViewModels;
using TotalPortal.Areas.Productions.Builders;

namespace TotalPortal.Areas.Productions.Controllers
{
    public class ProductionOrdersController : GenericViewDetailController<ProductionOrder, ProductionOrderDetail, ProductionOrderViewDetail, ProductionOrderDTO, ProductionOrderPrimitiveDTO, ProductionOrderDetailDTO, ProductionOrderViewModel>
    {
        public ProductionOrdersController(IProductionOrderService productionOrderService, IProductionOrderViewModelSelectListBuilder productionOrderViewModelSelectListBuilder)
            : base(productionOrderService, productionOrderViewModelSelectListBuilder, true)
        {
        }

        public override void AddRequireJsOptions()
        {
            base.AddRequireJsOptions();

            StringBuilder commodityTypeIDList = new StringBuilder();
            commodityTypeIDList.Append((int)GlobalEnums.CommodityTypeID.Items);
            commodityTypeIDList.Append(","); commodityTypeIDList.Append((int)GlobalEnums.CommodityTypeID.Materials);

            RequireJsOptions.Add("commodityTypeIDList", commodityTypeIDList.ToString(), RequireJsOptionsScope.Page);
        }

        public virtual ActionResult GetPendingFirmOrders()
        {
            this.AddRequireJsOptions();
            return View();
        }

    }

}

TotalSmartPortal/TotalPortal/Areas/Productions/Views/ProductionOrders/Approve.cshtml
@Html.Partial("Edit")
@Html.Partial("~/Views/Helpers/Commons/_ApproveConfirmed.cshtml")

TotalSmartPortal/TotalPortal/Areas/Productions/Views/ProductionOrders/CreateWizard.cshtml
@using TotalBase.Enums;
@using TotalPortal.Configuration;

@{Layout = "~/Views/Shared/_LayoutPopup.cshtml";}

@model TotalPortal.Areas.Productions.ViewModels.ProductionOrderViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Helpers/Bases/_BaseSectionTop.cshtml")

    @Html.HiddenFor(model => model.PlannedOrderID)
    @Html.HiddenFor(model => model.PlannedOrderCode)
    @Html.HiddenFor(model => model.PlannedOrderReference)
    @Html.HiddenFor(model => model.PlannedOrderEntryDate)
    @Html.HiddenFor(model => model.PlannedOrderDeliveryDate)

    @Html.HiddenFor(model => model.CustomerID)
    
    @Html.HiddenFor(model => model.Customer.CustomerID)
    @Html.HiddenFor(model => model.Customer.Code)
    @Html.HiddenFor(model => model.Customer.Name)
    @Html.HiddenFor(model => model.Customer.VATCode)
    @Html.HiddenFor(model => model.Customer.Telephone)
    @Html.HiddenFor(model => model.Customer.BillingAddress)
    @Html.HiddenFor(model => model.Customer.EntireTerritoryEntireName)
    @Html.HiddenFor(model => model.Customer.SalespersonID)
    @Html.HiddenFor(model => model.Customer.SalespersonName)
    @Html.HiddenFor(model => model.Customer.PaymentTermID)
    @Html.HiddenFor(model => model.Customer.PriceCategoryID)
    @Html.HiddenFor(model => model.Customer.PriceCategoryCode)

    @Html.HiddenFor(model => model.Description);

    @(Html.Kendo().TabStrip()
        .HtmlAttributes(new { @style = "height: 468px; margin-left: 0px; margin-right: 0px;" })
        .Name("tabStrip")
        .Items(tabStrip =>
        {
            tabStrip.Add().Text("Lệnh sản xuất theo kế hoạch sản xuất")
                .Content(@<text>
                    @Html.Partial("~/Areas/Productions/Views/ProductionOrders/_GetPlannedOrder.cshtml")
                </text>);
            tabStrip.Add().Text("Lệnh sản xuất tổng hợp theo khách hàng")
                    .Content(@<text>
                    @Html.Partial("~/Areas/Productions/Views/ProductionOrders/_GetCustomer.cshtml")
                    </text>);
        }).SelectedIndex(0)
    )


    <div class="background-bar" style="height: 45px;">
        <div class="popup-button-bar">
            <input id="submitCreateWizard" type="submit" formaction="@Url.Action("CreateWizard", "ProductionOrders")" formtarget="_top" style="display:none" />
            
            <button type="button" class="k-button" onclick="okButton_Click()"> <img src="~/Content/Images/Mains/Size24/Ok-1.png" /> Áp dụng khách hàng/KHSX đang chọn </button>
            <button type="button" class="k-button" onclick="okWOSelectButton_Click()"> <img src="~/Content/Images/Mains/Size24/Accept-Total.png" /> Lập lệnh sản xuất tổng hợp </button>
            <button type="button" class="k-button" onclick="window.parent.$('#myWindow').data('kendoWindow').close()"> <img src="~/Content/Images/Mains/Size24/Users-Exit-icon-24.png" /> Thoát </button>
        </div>
    </div>

}

<link href="@Url.Content("~/Content/CustomCss/GeneralPopup.css")" rel="stylesheet" type="text/css" />

<script type="text/javascript">
    function okButton_Click() {      
        handleOKEvent($($("#tabStrip").data("kendoTabStrip").select().index() === 0 ? "#productionOrderPendingPlannedOrderGrid" : "#productionOrderPendingCustomerGrid").data("kendoGrid"));
    }

    function okWOSelectButton_Click() {
        handleOKEvent();
    }

    function handleOKEvent(selectedGrid) { //This javascript is now used only here. Later, if it is used somewhere else, it should be break into a standalone js file, and then just only add a link here      

        if (selectedGrid === undefined)
            _setModelInput();
        else {
            var selectedDataItem = selectedGrid.dataItem(selectedGrid.select());
            if (selectedDataItem === undefined || selectedDataItem === null)
                return false;

            _setModelInput(selectedDataItem);
        }


        $("#submitCreateWizard").trigger("click");


        function _setModelInput(selectedDataItem) {

            $("#Customer_CustomerID").val(selectedDataItem === undefined || selectedDataItem.CustomerID === undefined ? null : selectedDataItem.CustomerID);
            $("#Customer_Code").val(selectedDataItem === undefined || selectedDataItem.CustomerCode === undefined ? null : selectedDataItem.CustomerCode);
            $("#Customer_Name").val(selectedDataItem === undefined || selectedDataItem.CustomerName === undefined ? null : selectedDataItem.CustomerName);
            $("#Customer_OfficialName").val(selectedDataItem === undefined || selectedDataItem.CustomerOfficialName === undefined ? null : selectedDataItem.CustomerOfficialName);
            $("#Customer_Birthday").val(selectedDataItem === undefined || selectedDataItem.CustomerBirthday === undefined ? null : kendo.toString(selectedDataItem.CustomerBirthday, Settings.DateFormat));
            $("#Customer_VATCode").val(selectedDataItem === undefined || selectedDataItem.CustomerVATCode === undefined ? null : selectedDataItem.CustomerVATCode);
            $("#Customer_Telephone").val(selectedDataItem === undefined || selectedDataItem.CustomerTelephone === undefined ? null : selectedDataItem.CustomerTelephone);
            $("#Customer_BillingAddress").val(selectedDataItem === undefined || selectedDataItem.CustomerBillingAddress === undefined ? null : selectedDataItem.CustomerBillingAddress);
            $("#Customer_ShippingAddress").val(selectedDataItem === undefined || selectedDataItem.CustomerShippingAddress === undefined ? null : selectedDataItem.CustomerShippingAddress);
            $("#Customer_TerritoryID").val(selectedDataItem === undefined || selectedDataItem.CustomerTerritoryID === undefined ? null : selectedDataItem.CustomerTerritoryID);
            $("#Customer_EntireTerritoryEntireName").val(selectedDataItem === undefined || selectedDataItem.CustomerEntireTerritoryEntireName === undefined ? null : selectedDataItem.CustomerEntireTerritoryEntireName);
            $("#Customer_SalespersonID").val(selectedDataItem === undefined || selectedDataItem.CustomerSalespersonID === undefined ? null : selectedDataItem.CustomerSalespersonID);
            $("#Customer_SalespersonName").val(selectedDataItem === undefined || selectedDataItem.CustomerSalespersonName === undefined ? null : selectedDataItem.CustomerSalespersonName);
            $("#Customer_PaymentTermID").val(selectedDataItem === undefined || selectedDataItem.PaymentTermID === undefined ? null : selectedDataItem.PaymentTermID);
            $("#Customer_PriceCategoryID").val(selectedDataItem === undefined || selectedDataItem.CustomerPriceCategoryID === undefined ? null : selectedDataItem.CustomerPriceCategoryID);
            $("#Customer_PriceCategoryCode").val(selectedDataItem === undefined || selectedDataItem.CustomerPriceCategoryCode === undefined ? null : selectedDataItem.CustomerPriceCategoryCode);

            $("#PlannedOrderID").val(selectedDataItem === undefined || selectedDataItem.PlannedOrderID === undefined ? null : selectedDataItem.PlannedOrderID);
            $("#PlannedOrderCode").val(selectedDataItem === undefined || selectedDataItem.PlannedOrderCode === undefined ? null : selectedDataItem.PlannedOrderCode);
            $("#PlannedOrderReference").val(selectedDataItem === undefined || selectedDataItem.PlannedOrderReference === undefined ? null : selectedDataItem.PlannedOrderReference);
            $("#PlannedOrderEntryDate").val(selectedDataItem === undefined || selectedDataItem.PlannedOrderEntryDate === undefined ? null : kendo.toString(selectedDataItem.PlannedOrderEntryDate, Settings.DateTimeFormat));
            $("#PlannedOrderDeliveryDate").val(selectedDataItem === undefined || selectedDataItem.PlannedOrderDeliveryDate === undefined ? null : kendo.toString(selectedDataItem.PlannedOrderDeliveryDate, Settings.DateTimeFormat));

            $("#Description").val(selectedDataItem === undefined || selectedDataItem.Description === undefined ? null : selectedDataItem.Description);        
        }
    }

</script>






TotalSmartPortal/TotalPortal/Areas/Productions/Views/ProductionOrders/Delete.cshtml
@Html.Partial("Edit")
@Html.Partial("~/Views/Helpers/Commons/_DeleteConfirm.cshtml")

TotalSmartPortal/TotalPortal/Areas/Productions/Views/ProductionOrders/Edit.cshtml
@model TotalPortal.Areas.Productions.ViewModels.ProductionOrderViewModel

@Html.Partial("_ProductionOrder")

TotalSmartPortal/TotalPortal/Areas/Productions/Views/ProductionOrders/GetPendingFirmOrders.cshtml
@using TotalModel.Models;
@using TotalPortal.Configuration;

@{Layout = "~/Views/Shared/_LayoutPopup.cshtml";}


@(Html.Kendo().Grid<ProductionOrderPendingFirmOrder>()
    .Name("gridPendingFirmOrders")
    .Columns(columns =>
    {
        columns.Bound(c => c.FirmOrderReference).Title("KHSX").Width(25).HtmlAttributes(new { @class = "grid-column-center" }).HeaderHtmlAttributes(new { @style = "text-align: center" });
        columns.Bound(c => c.FirmOrderCode).Title("Số CT").Width(25).HtmlAttributes(new { @class = "grid-column-center" }).HeaderHtmlAttributes(new { @style = "text-align: center" });
        columns.Bound(c => c.FirmOrderEntryDate).Title("Ngày KHSX").Width(39).Format("{0:" + Settings.DateFormat + "}").HtmlAttributes(new { @class = "grid-column-center" }).HeaderHtmlAttributes(new { @style = "text-align: center" });
        columns.Bound(c => c.FirmOrderDeliveryDate).Title("Giao hàng").Width(39).Format("{0:" + Settings.DateFormat + "}").HtmlAttributes(new { @class = "grid-column-center" }).HeaderHtmlAttributes(new { @style = "text-align: center" });
        columns.Bound(c => c.CustomerName).Title("Khách hàng").Width(60);
        columns.Bound(c => c.Specification).Title("Mã hàng").Width(68);        
        columns.Bound(c => c.Specs).Title("Tên hàng").Width(96);        
        columns.Bound(c => c.QuantityRemains).Title("SL").Format(Settings.kfmQuantity).Width(35).HtmlAttributes(new { @class = "grid-number-column" }).HeaderHtmlAttributes(new { @style = "text-align: right" });

        columns.Template(t => { }).Title("&nbsp;").ClientTemplate("<input class='IsSelected' #= IsSelected ? checked='checked':'' #  type='checkbox' />").Width(15).HtmlAttributes(new { @class = "grid-column-center" }).HeaderHtmlAttributes(new { @style = "text-align: center" });
    })
    .ToolBar(toolbar =>
    {
        toolbar.Template(@<text>
            <div class="toolbar" style="float: right;">
                <label>Nhập số KHSX, số chứng từ, tên khách hàng hoặc mã, tên thành phẩm</label>
                <input id="filterText" class="k-textbox" style="text-align: center; margin-right: 13px;" onkeyup="filterText_KeyUp()" />
            </div>
        </text>);
    })
    .Scrollable(s => s.Height(Settings.PopupContentHeightLarge))
    .DataSource(ds => ds.Ajax()
            .Read(read => read.Action("GetPendingFirmOrders", "ProductionOrderAPIs", new { area = "Productions" }).Data(@<text>
            function(e) {

            var productionOrderJSON = window.parent.$("#kendoGridDetails").data("kendoGrid").dataSource.data().toJSON();

            return {
            locationID: window.parent.requireConfig.pageOptions.LocationID,
            productionOrderID: window.parent.$("#ProductionOrderID").val(),
            plannedOrderID: window.parent.$("#PlannedOrderID").val(),
            customerID: window.parent.$("#Customer_CustomerID").val(),
            plannedOrderDetailIDs : productionOrderJSON.map(function(elem){return elem.FirmOrderID;}).join(","),
            isReadOnly: false
            };}
            </text>))
    .ServerOperation(false)) //If this is TRUE: Apply filter to datasource will call Ajax to get new datasource result. If this is FALSE: filter will run on client
    .Selectable()
)


<div class="background-bar" style="height: 45px;">
    <div class="popup-button-bar">
        <button type="button" class="k-button" onclick="okButton_Click()"> <img src="~/Content/Images/Mains/Size24/Actions-bookmark-add-icon-24.png" /> Thêm vào lệnh</button>
        <button type="button" class="k-button" onclick="cancelButton_Click()"> <img src="~/Content/Images/Mains/Size24/Users-Exit-icon-24.png" /> Thoát </button>
    </div>
</div>

<script src="@Url.Content("~/Scripts/Controllers/Productions/ProductionOrders/AddPendingFirmOrder.js")"></script>

<script type="text/javascript">
    function okButton_Click() {        
        handleOKEvent(window.parent.$("#kendoGridDetails").data("kendoGrid").dataSource, $("#gridPendingFirmOrders").data("kendoGrid").dataSource);
    }

    $('#gridPendingFirmOrders').on('click', '.IsSelected', function () {
        var checked = $(this).is(':checked');
        var grid = $('#gridPendingFirmOrders').data().kendoGrid;
        var dataItem = grid.dataItem($(this).closest('tr'));
        dataItem.set('IsSelected', checked);
    })
</script>



<script>
    function filterText_KeyUp() {
        var filterText = $("#filterText").val(), gridDetails = $("#gridPendingFirmOrders").data("kendoGrid");

        if (filterText && filterText.length >= "@Settings.AutoCompleteMinLenght") {
            gridDetails.dataSource.filter({
                logic: "or",
                filters: [
                    { field: "FirmOrderCode", operator: "contains", value: filterText },
                    { field: "FirmOrderReference", operator: "contains", value: filterText },

                    { field: "CommodityCode", operator: "contains", value: filterText },
                    { field: "CommodityName", operator: "contains", value: filterText },

                    { field: "CustomerName", operator: "contains", value: filterText },

                    { field: "Specs", operator: "contains", value: filterText },   
                    { field: "Specification", operator: "contains", value: filterText }                    
                    
                ]
            });


        } else {
            if (gridDetails.dataSource.filter() != undefined)
                gridDetails.dataSource.filter({});
        }
    }
</script>

TotalSmartPortal/TotalPortal/Areas/Productions/Views/ProductionOrders/Index.cshtml
@using TotalPortal.Configuration

<div id="popupWindow"></div>

<div>
    @(Html.Kendo().Grid<TotalModel.Models.ProductionOrderIndex>()
            .Name("kendoGridIndex")
            .Columns(columns =>
            {
                columns.Bound(p => p.ProductionOrderID).DisplayNameTitle().Hidden();                
                columns.Bound(p => p.EntryDate).Title("Ngày").Format("{0:dd/MM/yyyy}").Hidden();

                columns.Bound(p => p.Reference).Title("#").Width(10).ClientTemplate("<a href='" + Url.RouteUrl("Default", new { controller = "Productions/ProductionOrders", action = "Edit" }) + "/#= ProductionOrderID #'>#=Reference#</a>");
                columns.Bound(p => p.PlannedOrderReference).Title("Số KHSX").HtmlAttributes(new { @class = "grid-column-center" }).HeaderHtmlAttributes(new { @style = "text-align: center" }).Width(10);
                columns.Bound(p => p.PlannedOrderCode).Title("Số CT").HtmlAttributes(new { @class = "grid-column-center" }).HeaderHtmlAttributes(new { @style = "text-align: center" }).Width(10);
                columns.Bound(p => p.PlannedOrderDeliveryDate).Title("G/H").Format("{0:dd/MM/yyyy}").HtmlAttributes(new { @class = "grid-column-center" }).HeaderHtmlAttributes(new { @style = "text-align: center" }).Width(5);
                columns.Bound(p => p.CustomerName).Title("Khách hàng").Width(68);
                columns.Bound(p => p.Caption).Title("Mặt hàng").Width(127);
                columns.Bound(p => p.Description).Title("Diễn giải").Width(108);
                columns.Bound(p => p.VoidTypeName).Title("Hủy").Width(10);

                columns.Template(model => null).HtmlAttributes(new { @class = "grid-column-center" }).Width(68)
                    .ClientTemplate("<a class='k-button' style='padding-left:5px; min-width:28px; width:28px' href='" + Url.RouteUrl("Default", new { controller = "Productions/ProductionOrders", action = "Void" }) + "/#= ProductionOrderID #'><span class='k-icon k-edit'></span></a> <a class='k-button' style='padding-left:0px; padding-right:0px; min-width:28px; width:28px' href='" + Url.RouteUrl("Default", new { controller = "Productions/ProductionOrders", action = "Delete" }) + "/#= ProductionOrderID #'><span class='k-icon k-delete'></span></a>");
            })
            .ToolBar(toolbar =>
            {
                toolbar.Template(@<text>
                    <button type="button" class="k-button" onclick="createWizard()"> <img src="~/Content/Images/Mains/Size24/folder-documents-icon-24.png" /> Lập lệnh sản xuất </button>
                    <div class="toolbar" style="float: right;">
                        <label>Nhập số phiếu hoặc tên khách hàng để tìm</label>
                        <input id="indexFilterText" class="k-textbox" style="text-align: center; " onkeyup="indexFilterText_KeyUp()" />
                    </div>
                </text>);
            })
            .Filterable(f => f.Enabled(false))            
            .Pageable()
            .Groupable(g => g.Messages(messages => messages.Empty("Phân nhóm dữ liệu: Kéo và thả tiêu đề một hoặc nhiều cột dữ liệu ngay bên dưới vào đây để phân nhóm hiển thị theo phân cấp của các cột dữ liệu")))                        
            .Selectable()
            .Sortable()
            .Events(e =>
            {
                e.DataBound("hightLightSelectedRow");
            })
            .DataSource(dataSource => dataSource
                .Ajax()
                .Group(group => group.AddDescending(p => p.EntryDate))
                .Read(read => read.Action("GetProductionOrderIndexes", "ProductionOrderAPIs", new { area = "Productions" }))
                .Sort(sort =>
                    {
                        sort.Add(p => p.EntryDate).Descending();
                        sort.Add(p => p.ProductionOrderID).Descending();
                    })
                .PageSize(20)
                .Model(model =>
                {
                    model.Id(x => x.ProductionOrderID);
                    model.Field(m => m.ProductionOrderID).DefaultValue(0);
                })
                .ServerOperation(true)
                )
            .HtmlAttributes(new { @class = "grid-class" }))
</div>



<script type="text/javascript">
    function hightLightSelectedRow(e) {
        require(["kindexGrid"], function (kindexGrid) {
            var kindexGridInstance = new kindexGrid("kendoGridIndex");
            kindexGridInstance.setSelectedRow("ProductionOrderID", '@ViewBag.SelectedEntityID');
        });
    }

    function createWizard() {
        require(["kpopupWindow"], function (kpopupWindow) {
            var createWizardWindow = new kpopupWindow();
            createWizardWindow.openWindow($("#popupWindow"), "@Url.Action("CreateWizard", "ProductionOrders")", "Chọn khách hàng, lệnh sản xuất", "@Settings.PopupWidth", "@Settings.PopupHeightWithTab");
        });
    }


    decoratingKindex = function (idx, elem) {

        if (elem.Approved == null || elem.Approved == false) {
            $('tr[data-uid="' + elem.uid + '"]').addClass("NotApproved");
        }
        else
        {
            if (elem.InActive != null && elem.InActive == true) {
                $('tr[data-uid="' + elem.uid + '"]').addClass("isBonus");
            }

            if (elem.InActivePartial != null && elem.InActivePartial == true) {
                $('tr[data-uid="' + elem.uid + '"]').addClass("isBonus1");
            }
        }

    }






    function indexFilterText_KeyUp() {
        var indexFilterText = $("#indexFilterText").val(), gridDetails = $("#kendoGridIndex").data("kendoGrid");

        if (indexFilterText && indexFilterText.length >= "@Settings.AutoCompleteMinLenght") {
            gridDetails.dataSource.filter({
                logic: "or",
                filters: [
                    { field: "Code", operator: "contains", value: indexFilterText },
                    { field: "Reference", operator: "contains", value: indexFilterText }
                ]
            });


        } else {
            if (gridDetails.dataSource.filter() != undefined)
                gridDetails.dataSource.filter({});
        }
    }

</script>




TotalSmartPortal/TotalPortal/Areas/Productions/Views/ProductionOrders/Print.cshtml
@using MvcReportViewer;
@model TotalPortal.ViewModels.Helpers.PrintViewModel

@Html.MvcReportViewerFluent("/TotalSmartPortal/ProductionOrderSheet").ReportParameters(new { ProductionOrderID = @Model.Id, CurrentHost = HttpContext.Current.Request.Url.Host }).Attributes(new { Height = 1100, Width = 1150, style = "border: none" }).ControlSettings(new ControlSettings() { ShowParameterPrompts = false })

TotalSmartPortal/TotalPortal/Areas/Productions/Views/ProductionOrders/Void.cshtml
@Html.Partial("Edit")
@Html.Partial("~/Views/Helpers/Commons/_VoidConfirmed.cshtml")

TotalSmartPortal/TotalPortal/Areas/Productions/Views/ProductionOrders/VoidDetailSuccess.cshtml
@model TotalPortal.ViewModels.Helpers.VoidDetailViewModel

@{Layout = "~/Views/Shared/_LayoutPopup.cshtml";}

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.DetailID)
    @Html.HiddenFor(model => model.InActivePartial)
    @Html.HiddenFor(model => model.VoidType.Name)
}

<script type="text/javascript">
    $(document).ready(function () {
        var kenGrid = window.parent.$("#kendoGridDetails").data("kendoGrid");
        var data = kenGrid.dataSource.data();

        $.each(data, function (i, row) {
            if (row.ProductionOrderDetailID == $("#DetailID").val()) {

                //This will raise kendo grid DataBound event (to style grid row). Now: we set only one field to raise DataBound event one time only. (The control will raise event per each row.set command)
                row.set("VoidTypeName", ($("#InActivePartial").val() == 'True' ? $("#VoidType_Name").val() : ''));
                //Important note: this Success response does not set all necessary fields for the model, ex: InActivePartial, VoidTypeID, ...
                //So: Never submit model to save to database when in void mode

                //Note: Don't remove this code for later refer as an example of how to add/  remove style to current gird.
                //if ($("#InActivePartial").val() == 'True' && window.parent.$('tr[data-uid="' + row.uid + '"]').hasClass("isBonus") == false)
                //    window.parent.$('tr[data-uid="' + row.uid + '"]').addClass("isBonus");
                //if ($("#InActivePartial").val() == 'False' && window.parent.$('tr[data-uid="' + row.uid + '"]').hasClass("isBonus") == true)
                //    window.parent.$('tr[data-uid="' + row.uid + '"]').removeClass("isBonus");

                return false;
            }
        });

        window.parent.$("#myWindow").data("kendoWindow").close();
    });
</script>