TotalSmartPortal/TotalPortal/Areas/Inventories/ViewModels/GoodsIssueViewModel.cs
using System.Web.Mvc;
using System.Collections.Generic;

using TotalDTO.Inventories;
using TotalPortal.Builders;
using TotalPortal.ViewModels.Helpers;
using TotalPortal.Areas.Commons.ViewModels.Helpers;

namespace TotalPortal.Areas.Inventories.ViewModels
{
    public class GoodsIssueViewModel : GoodsIssueDTO, IViewDetailViewModel<GoodsIssueDetailDTO>, IPreparedPersonDropDownViewModel, IApproverDropDownViewModel, IPaymentTermDropDownViewModel, IA02SimpleViewModel
    {
        public IEnumerable<SelectListItem> AspNetUserSelectList { get; set; }
        public IEnumerable<SelectListItem> PaymentTermSelectList { get; set; }

        public override bool PrintAfterClosedSubmit { get { return true; } }
    }

}

TotalSmartPortal/TotalPortal/ViewModels/Helpers/PrintViewModel.cs
namespace TotalPortal.ViewModels.Helpers
{
    public class PrintViewModel
    {
        public int? Id { get; set; }
        public int? DetailID { get; set; }

        public int? FilterID { get; set; }

        public int LocationID { get; set; }

        public string ServerName { get { return "DATA-SERVER"; } }
        public string CatalogName { get { return "TotalSmartPortal"; } }

        public string ReportFolder { get { return "TotalSmartPortal"; } }
        public string ReportPath { get; set; }

        public int PrintOptionID { get; set; }
    }
}

TotalSmartPortal/TotalPortal/Areas/Inventories/Controllers/GoodsIssuesController.cs
using System.Collections.Generic;

using TotalModel.Models;

using TotalDTO.Inventories;
using TotalCore.Repositories.Commons;
using TotalCore.Services.Inventories;

using TotalPortal.Controllers;

using TotalPortal.APIs.Sessions;

using TotalPortal.Areas.Inventories.ViewModels;
using TotalPortal.Areas.Inventories.Builders;
using TotalPortal.Areas.Inventories.Controllers.Sessions;

namespace TotalPortal.Areas.Inventories.Controllers
{
    public class GoodsIssuesController : GenericViewDetailController<GoodsIssue, GoodsIssueDetail, GoodsIssueViewDetail, GoodsIssueDTO, GoodsIssuePrimitiveDTO, GoodsIssueDetailDTO, GoodsIssueViewModel>
    {
        private readonly ICustomerRepository customerRepository;
        private readonly IGoodsIssueService goodsIssueService;

        public GoodsIssuesController(IGoodsIssueService goodsIssueService, IGoodsIssueViewModelSelectListBuilder goodsIssueViewModelSelectListBuilder, ICustomerRepository customerRepository)
            : base(goodsIssueService, goodsIssueViewModelSelectListBuilder, true)
        {
            this.goodsIssueService = goodsIssueService;
            this.customerRepository = customerRepository;
        }


        protected override ICollection<GoodsIssueViewDetail> GetEntityViewDetails(GoodsIssueViewModel goodsIssueViewModel)
        {
            ICollection<GoodsIssueViewDetail> goodsIssueViewDetails = this.goodsIssueService.GetGoodsIssueViewDetails(goodsIssueViewModel.GoodsIssueID, this.goodsIssueService.LocationID, goodsIssueViewModel.DeliveryAdviceID == null ? 0 : (int)goodsIssueViewModel.DeliveryAdviceID, goodsIssueViewModel.CustomerID, goodsIssueViewModel.ReceiverID, goodsIssueViewModel.WarehouseID == null ? 0 : (int)goodsIssueViewModel.WarehouseID, goodsIssueViewModel.ShippingAddress, goodsIssueViewModel.Addressee == null ? "" : goodsIssueViewModel.Addressee, goodsIssueViewModel.TradePromotionID, goodsIssueViewModel.VATPercent, false);

            return goodsIssueViewDetails;
        }

        protected override bool GetShowDiscount(GoodsIssueViewModel simpleViewModel)
        {
            return base.GetShowDiscount(simpleViewModel) || this.customerRepository.GetShowDiscount(simpleViewModel == null ? 0 : simpleViewModel.CustomerID);
        }

        protected override GoodsIssueViewModel InitViewModelByPrior(GoodsIssueViewModel simpleViewModel)
        {
            simpleViewModel = base.InitViewModelByPrior(simpleViewModel);
            if (simpleViewModel.CustomerID > 0 && simpleViewModel.DeliveryAdviceID == null)
            {
                List<PendingDeliveryAdviceDescription> pendingDeliveryAdviceDescriptions = this.goodsIssueService.GetDescriptions(this.goodsIssueService.LocationID, simpleViewModel.CustomerID, simpleViewModel.ReceiverID, (simpleViewModel.WarehouseID != null ? (int)simpleViewModel.WarehouseID : 0), simpleViewModel.ShippingAddress, simpleViewModel.Addressee, simpleViewModel.TradePromotionID, simpleViewModel.VATPercent);

                string description = ""; string remarks = "";
                pendingDeliveryAdviceDescriptions.ForEach(e =>
                {
                    if (e.Description != null && e.Description != "")
                        description = description + (description != "" ? ", " : "") + e.Reference + ": " + e.Description;
                    if (e.Remarks != null && e.Remarks != "")
                        remarks = remarks + (remarks != "" ? ", " : "") + e.Reference + ": " + e.Remarks;
                });
                simpleViewModel.Description = description; simpleViewModel.Remarks = remarks;
            }

            return simpleViewModel;
        }


        protected override GoodsIssueViewModel InitViewModelByDefault(GoodsIssueViewModel simpleViewModel)
        {
            simpleViewModel = base.InitViewModelByDefault(simpleViewModel);

            if (simpleViewModel.Storekeeper == null)
            {
                string storekeeperSession = GoodsIssueSession.GetStorekeeper(this.HttpContext);

                if (HomeSession.TryParseID(storekeeperSession) > 0)
                {
                    simpleViewModel.Storekeeper = new TotalDTO.Commons.EmployeeBaseDTO();
                    simpleViewModel.Storekeeper.EmployeeID = (int)HomeSession.TryParseID(storekeeperSession);
                    simpleViewModel.Storekeeper.Name = HomeSession.TryParseName(storekeeperSession);
                }
            }

            return simpleViewModel;
        }

        protected override void BackupViewModelToSession(GoodsIssueViewModel simpleViewModel)
        {
            base.BackupViewModelToSession(simpleViewModel);
            GoodsIssueSession.SetStorekeeper(this.HttpContext, simpleViewModel.Storekeeper.EmployeeID, simpleViewModel.Storekeeper.Name);
        }
    }
}

TotalSmartPortal/TotalPortal/Areas/Inventories/Views/GoodsIssues/Approve.cshtml
@Html.Partial("Edit")
@Html.Partial("~/Views/Helpers/Commons/_ApproveConfirmed.cshtml")

TotalSmartPortal/TotalPortal/Areas/Inventories/Views/GoodsIssues/CreateWizard.cshtml
@{Layout = "~/Views/Shared/_LayoutPopup.cshtml";}

@model TotalPortal.Areas.Inventories.ViewModels.GoodsIssueViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Helpers/Bases/_BaseSectionTop.cshtml")
    
    @Html.HiddenFor(model => model.GoodsIssueID);

    @Html.HiddenFor(model => model.Code);
    
    @Html.HiddenFor(model => model.ShippingAddress);
    @Html.HiddenFor(model => model.Addressee);
    @Html.HiddenFor(model => model.PaymentTermID);

    @Html.HiddenFor(model => model.VATbyRow);    
    @Html.HiddenFor(model => model.VATPercent);

    @Html.HiddenFor(model => model.TradePromotionID);
    @Html.HiddenFor(model => model.TradePromotionSpecs);
    @Html.HiddenFor(model => model.TradeDiscountRate);

    @Html.HiddenFor(model => model.Description);
    @Html.HiddenFor(model => model.Remarks);

    @Html.HiddenFor(model => model.Customer.CustomerID);
    @Html.HiddenFor(model => model.Customer.Code);
    @Html.HiddenFor(model => model.Customer.Name);
    @Html.HiddenFor(model => model.Customer.VATCode);
    @Html.HiddenFor(model => model.Customer.Telephone);
    @Html.HiddenFor(model => model.Customer.BillingAddress);
    @Html.HiddenFor(model => model.Customer.EntireTerritoryEntireName);
    @Html.HiddenFor(model => model.Customer.SalespersonID)
    @Html.HiddenFor(model => model.Customer.SalespersonName)
    
    @Html.HiddenFor(model => model.Receiver.CustomerID);
    @Html.HiddenFor(model => model.Receiver.Code);
    @Html.HiddenFor(model => model.Receiver.Name);
    @Html.HiddenFor(model => model.Receiver.VATCode);
    @Html.HiddenFor(model => model.Receiver.Telephone);
    @Html.HiddenFor(model => model.Receiver.BillingAddress);
    @Html.HiddenFor(model => model.Receiver.EntireTerritoryEntireName);
    @Html.HiddenFor(model => model.Receiver.SalespersonID)
    @Html.HiddenFor(model => model.Receiver.SalespersonName)
    
    @Html.HiddenFor(model => model.Warehouse.WarehouseID);
    @Html.HiddenFor(model => model.Warehouse.Code);
    @Html.HiddenFor(model => model.Warehouse.Name);
    
    @Html.HiddenFor(model => model.DeliveryAdvice.DeliveryAdviceID);
    @Html.HiddenFor(model => model.DeliveryAdvice.Reference);
    @Html.HiddenFor(model => model.DeliveryAdvice.EntryDate);

    @Html.HiddenFor(model => model.Storekeeper.EmployeeID);
    @Html.HiddenFor(model => model.Storekeeper.Name);

    @(Html.Kendo().TabStrip()
        .HtmlAttributes(new { @style = "height: 468px; margin-left: 0px; margin-right: 0px;" })
        .Name("tabStrip")
        .Items(tabStrip =>
        {
            tabStrip.Add().Text("Chọn phiếu đề nghị giao hàng")
                .Selected(true)
                .Content(@<text>
            @Html.Partial("~/Areas/Inventories/Views/GoodsIssues/_GetDeliveryAdvice.cshtml")
                </text>);

            tabStrip.Add().Text("Lập phiếu xuất kho tổng hợp của nhiều phiếu ĐNGH")
                .Content(@<text>
                    @Html.Partial("~/Areas/Inventories/Views/GoodsIssues/_GetCustomer.cshtml")
                </text>);
        })
    )


    <div class="background-bar" style="height: 45px;">
        <div class="popup-button-bar">
            <input id="submitCreateWizard" type="submit" formaction="@Url.Action("CreateWizard", "GoodsIssues")" formtarget="_top" style="display:none" />

            <button type="button" class="k-button" onclick="okButton_Click()"> <img src="~/Content/Images/Mains/Size24/Ok-1.png" /> Xuất kho cho khách hàng đang chọn </button>
            <button type="button" class="k-button" onclick="window.parent.$('#myWindow').data('kendoWindow').close()"> <img src="~/Content/Images/Mains/Size24/Users-Exit-icon-24.png" /> Thoát </button>
        </div>
    </div>
}

<link href="@Url.Content("~/Content/CustomCss/GeneralPopup.css")" rel="stylesheet" type="text/css" />


<script type="text/javascript">
    function okButton_Click() {
        handleOKEvent($("#tabStrip").data("kendoTabStrip").select().index());
    }


    function handleOKEvent(tabIndex) {
        if (tabIndex === undefined)
            _setModelInput();
        else {
            var selectedGrid = $(tabIndex === 0 ? "#pendingDeliveryAdviceGrid" : "#pendingDeliveryAdviceCustomerGrid").data("kendoGrid");
            var selectedDataItem = selectedGrid.dataItem(selectedGrid.select());
            if (selectedDataItem === undefined || selectedDataItem === null)
                return false;

            _setModelInput(selectedDataItem);
        }
        $("#submitCreateWizard").trigger("click");


        function _setModelInput(selectedDataItem) {

            $("#Code").val(selectedDataItem === undefined || selectedDataItem.DeliveryAdviceCode === undefined ? null : selectedDataItem.DeliveryAdviceCode);

            $("#DeliveryAdvice_DeliveryAdviceID").val(selectedDataItem === undefined || selectedDataItem.DeliveryAdviceID === undefined ? null : selectedDataItem.DeliveryAdviceID);
            $("#DeliveryAdvice_Reference").val(selectedDataItem === undefined || selectedDataItem.DeliveryAdviceReference === undefined ? null : selectedDataItem.DeliveryAdviceReference);
            $("#DeliveryAdvice_EntryDate").val(selectedDataItem === undefined || selectedDataItem.DeliveryAdviceEntryDate === undefined ? null : kendo.toString(selectedDataItem.DeliveryAdviceEntryDate, Settings.DateFormat));

            $("#Warehouse_WarehouseID").val(selectedDataItem === undefined || selectedDataItem.WarehouseID === undefined ? null : selectedDataItem.WarehouseID);
            $("#Warehouse_Code").val(selectedDataItem === undefined || selectedDataItem.WarehouseCode === undefined ? null : selectedDataItem.WarehouseCode);
            $("#Warehouse_Name").val(selectedDataItem === undefined || selectedDataItem.WarehouseName === undefined ? null : selectedDataItem.WarehouseName);

            $("#ShippingAddress").val(selectedDataItem === undefined || selectedDataItem.ShippingAddress === undefined ? null : selectedDataItem.ShippingAddress);
            $("#Addressee").val(selectedDataItem === undefined || selectedDataItem.Addressee === undefined ? null : selectedDataItem.Addressee);

            $("#PaymentTermID").val(selectedDataItem === undefined || selectedDataItem.PaymentTermID === undefined ? null : selectedDataItem.PaymentTermID);

            $("#TradePromotionID").val(selectedDataItem === undefined || selectedDataItem.TradePromotionID === undefined ? null : selectedDataItem.TradePromotionID);
            $("#TradePromotionSpecs").val(selectedDataItem === undefined || selectedDataItem.TradePromotionSpecs === undefined ? null : selectedDataItem.TradePromotionSpecs);
            $("#TradeDiscountRate").val(selectedDataItem === undefined || selectedDataItem.TradeDiscountRate === undefined ? null : selectedDataItem.TradeDiscountRate);
            $("#VATPercent").val(selectedDataItem === undefined || selectedDataItem.VATPercent === undefined ? null : selectedDataItem.VATPercent);

            $("#Description").val(selectedDataItem === undefined || selectedDataItem.Description === undefined ? null : selectedDataItem.Description);
            $("#Remarks").val(selectedDataItem === undefined || selectedDataItem.Remarks === undefined ? null : selectedDataItem.Remarks);

            $("#Customer_CustomerID").val(selectedDataItem === undefined ? null : selectedDataItem.CustomerID);
            $("#Customer_Code").val(selectedDataItem === undefined ? null : selectedDataItem.CustomerCode);
            $("#Customer_Name").val(selectedDataItem === undefined ? null : selectedDataItem.CustomerName);
            $("#Customer_VATCode").val(selectedDataItem === undefined ? null : selectedDataItem.CustomerVATCode);
            $("#Customer_Telephone").val(selectedDataItem === undefined ? null : selectedDataItem.CustomerTelephone);
            $("#Customer_BillingAddress").val(selectedDataItem === undefined ? null : selectedDataItem.CustomerBillingAddress);
            $("#Customer_EntireTerritoryEntireName").val(selectedDataItem === undefined ? null : selectedDataItem.CustomerEntireTerritoryEntireName);


            $("#Receiver_CustomerID").val(selectedDataItem === undefined ? null : selectedDataItem.ReceiverID);
            $("#Receiver_Code").val(selectedDataItem === undefined ? null : selectedDataItem.ReceiverCode);
            $("#Receiver_Name").val(selectedDataItem === undefined ? null : selectedDataItem.ReceiverName);
            $("#Receiver_VATCode").val(selectedDataItem === undefined ? null : selectedDataItem.ReceiverVATCode);
            $("#Receiver_Telephone").val(selectedDataItem === undefined ? null : selectedDataItem.ReceiverTelephone);
            $("#Receiver_BillingAddress").val(selectedDataItem === undefined ? null : selectedDataItem.ReceiverBillingAddress);
            $("#Receiver_EntireTerritoryEntireName").val(selectedDataItem === undefined ? null : selectedDataItem.ReceiverEntireTerritoryEntireName);

        }
    }

</script>

TotalSmartPortal/TotalPortal/Areas/Inventories/Views/GoodsIssues/Delete.cshtml
@Html.Partial("Edit")
@Html.Partial("~/Views/Helpers/Commons/_DeleteConfirm.cshtml")

TotalSmartPortal/TotalPortal/Areas/Inventories/Views/GoodsIssues/Edit.cshtml
@model TotalPortal.Areas.Inventories.ViewModels.GoodsIssueViewModel

@Html.Partial("_GoodsIssue")

TotalSmartPortal/TotalPortal/Areas/Inventories/Views/GoodsIssues/Index.cshtml
@using TotalPortal.Configuration

<div id="popupWindow"></div>

<div>
    @(Html.Kendo().Grid<TotalModel.Models.GoodsIssueIndex>()
        .Name("kendoGridIndex")
        .Columns(columns =>
        {
            columns.Bound(p => p.GoodsIssueID).DisplayNameTitle().Hidden();            
            columns.Bound(p => p.EntryDate).Title("Ngày").Format("{0:dd/MM/yyyy}").Width(20);
            columns.Bound(p => p.Reference).Title("PXK").Width(20).ClientTemplate("<a href='" + Url.RouteUrl("Default", new { controller = "Inventories/GoodsIssues", action = "Edit" }) + "/#= GoodsIssueID #'>#=Reference#</a>");
            columns.Bound(p => p.DeliveryAdviceReferences).Title("ĐNGH").Width(60);
            columns.Bound(p => p.GoodsIssueCode).Title("ĐH").Width(60);
            columns.Bound(p => p.CustomerName).Title("Khách hàng").Width(250);
            columns.Bound(p => p.ReceiverDescription).Title("Giao hàng").Width(250);
            columns.Bound(p => p.Description).Title("Diễn giải").Width(150);

            columns.Bound(p => p.TotalQuantity).Title("Số lượng").Format(Settings.kfmQuantity).Width(60).HtmlAttributes(new { @class = "grid-number-column" }).HeaderHtmlAttributes(new { @style = "text-align: right"}).Filterable(false).ClientFooterTemplate("#= kendo.format('" + Settings.kfmQuantity + "', sum) #").FooterHtmlAttributes(new { @class = "grid-number-column" });

            columns.Bound(p => p.TotalListedGrossAmount).Title("Thành tiền").Format(Settings.kfmAmount).HtmlAttributes(new { @class = "grid-number-column" }).HeaderHtmlAttributes(new { @style = "text-align: right"}).Filterable(false).Width(90).ClientFooterTemplate("#= kendo.format('" + Settings.kfmAmount + "', sum) #").FooterHtmlAttributes(new { @class = "grid-number-column" }).Hidden(@ViewBag.ShowDiscount ? true : false);
            columns.Bound(p => p.TotalGrossAmount).Title("Thành tiền").Format(Settings.kfmAmount).HtmlAttributes(new { @class = "grid-number-column" }).HeaderHtmlAttributes(new { @style = "text-align: right"}).Filterable(false).Width(90).ClientFooterTemplate("#= kendo.format('" + Settings.kfmAmount + "', sum) #").FooterHtmlAttributes(new { @class = "grid-number-column" }).Hidden(@ViewBag.ShowDiscount ? false : true);

            columns.Template(model => null).HtmlAttributes(new { @class = "grid-column-center" }).Width(88)
                .ClientTemplate("<a class='k-button' style='padding-left:5px; min-width:28px; width:28px' href='" + Url.RouteUrl("Default", new { controller = "Inventories/GoodsIssues", action = "Edit" }) + "/#= GoodsIssueID #'><span class='k-icon k-edit'></span></a> <a class='k-button' style='padding-left:0px; padding-right:0px; min-width:28px; width:28px' href='" + Url.RouteUrl("Default", new { controller = "Inventories/GoodsIssues", action = "Delete" }) + "/#= GoodsIssueID #'><span class='k-icon k-delete'></span></a>");
        })
        .ToolBar(toolbar =>
        {
            toolbar.Template(@<text> 
                <button type="button" class="k-button" onclick="createWizard()"> <img src="~/Content/Images/Mains/Size24/folder-documents-icon-24.png" /> Lập phiếu xuất kho </button> 
                <div class="toolbar" style="float: right;">
                    <label>Nhập số phiếu xuất kho, hoặc phiếu ĐNGH hoặc tên khách hàng để tìm</label>
                    <input id="indexFilterText" class="k-textbox" style="text-align: center; " onkeyup="indexFilterText_KeyUp()" />
                </div>
            </text>);
        })

        .Pageable()
        .Groupable(g => g.Messages(messages => messages.Empty("Phân nhóm dữ liệu: Kéo và thả tiêu đề một hoặc nhiều cột dữ liệu ngay bên dưới vào đây để phân nhóm hiển thị theo phân cấp của các cột dữ liệu")))        
        .Selectable()
        .Sortable()
        .Events(e =>
        {
            e.DataBound("hightLightSelectedRow");
        })
        .DataSource(dataSource => dataSource
            .Ajax()
            .Read(read => read.Action("GetGoodsIssueIndexes", "GoodsIssueAPIs"))
            .Sort(sort =>
                {
                    sort.Add(p => p.EntryDate).Descending();
                    sort.Add(p => p.GoodsIssueID).Descending();
                })
            .PageSize(20)
            .Model(model =>
            {
                model.Id(x => x.GoodsIssueID);
                model.Field(m => m.GoodsIssueID).DefaultValue(0);
            })
            .ServerOperation(true)
            .Aggregates(a => a.Add(x => x.TotalQuantity).Sum())
            .Aggregates(a => a.Add(x => x.TotalListedGrossAmount).Sum())
            .Aggregates(a => a.Add(x => x.TotalGrossAmount).Sum())
            )
            .HtmlAttributes(new { @class = "grid-class" })
    )
</div>




<script type="text/javascript">
    function hightLightSelectedRow(e) {
        require(["kindexGrid"], function (kindexGrid) {
            var kindexGridInstance = new kindexGrid("kendoGridIndex");
            kindexGridInstance.setSelectedRow("GoodsIssueID", '@ViewBag.SelectedEntityID');
        });
    }

    function createWizard() {
        require(["kpopupWindow"], function (kpopupWindow) {
            var createWizardWindow = new kpopupWindow();
            createWizardWindow.openWindow($("#popupWindow"), "@Url.Action("CreateWizard", "GoodsIssues")", "Chọn đề nghị giao hàng", "@Settings.PopupWidthLarge", "@Settings.PopupHeightWithTab");
        });
    }

    decoratingKindex = function (idx, elem) {
        if (elem.Approved == null || elem.Approved == false) {
            $('tr[data-uid="' + elem.uid + '"]').addClass("NotApproved");
        }
    }








    function indexFilterText_KeyUp() {
        var indexFilterText = $("#indexFilterText").val(), gridDetails = $("#kendoGridIndex").data("kendoGrid");

        if (indexFilterText && indexFilterText.length >= "@Settings.AutoCompleteMinLenght") {
            gridDetails.dataSource.filter({
                logic: "or",
                filters: [
                    { field: "Reference", operator: "contains", value: indexFilterText },
                    { field: "DeliveryAdviceReferences", operator: "contains", value: indexFilterText },
                    { field: "CustomerName", operator: "contains", value: indexFilterText }
                ]
            });


        } else {
            if (gridDetails.dataSource.filter() != undefined)
                gridDetails.dataSource.filter({});
        }
    }

</script>

TotalSmartPortal/TotalPortal/Areas/Inventories/Views/GoodsIssues/Open.cshtml
@model TotalPortal.Areas.Inventories.ViewModels.GoodsIssueViewModel

@Html.Partial("_GoodsIssue")

TotalSmartPortal/TotalPortal/Areas/Inventories/Views/GoodsIssues/Print.cshtml
@using MvcReportViewer;
@model TotalPortal.ViewModels.Helpers.PrintViewModel

@Html.MvcReportViewerFluent("/TotalSmartPortal/GoodsIssueSheet").ReportParameters(new { GoodsIssueID = @Model.Id }).Attributes(new { Height = 1100, Width = 1150, style = "border: none" }).ControlSettings(new ControlSettings() { ShowParameterPrompts = false })

TotalSmartPortal/TotalPortal/Areas/Inventories/Views/GoodsIssues/_GetCustomer.cshtml

@using TotalPortal.Configuration
@using TotalModel.Models;

@(Html.Kendo().Grid<PendingDeliveryAdviceCustomer>()
    .Name("pendingDeliveryAdviceCustomerGrid")

    .Columns(columns =>
    {
        columns.Bound(c => c.WarehouseCode).Title("Kho").Width(35);
        columns.Bound(c => c.CustomerCode).Title("Mã khách hàng").Width(90);
        columns.Bound(c => c.CustomerName).Title("Tên khách hàng").Width(200);
        columns.Bound(c => c.TradePromotionSpecs).Title("CK tổng").Width(100);
        columns.Bound(c => c.Addressee).Title("Người nhận").Width(100);
        columns.Bound(c => c.ReceiverDescription).Title("Giao hàng").Width(180);
    })
    .ToolBar(toolbar =>
    {
        toolbar.Template(@<text>
            <div class="toolbar" style="float: right;">
                <label>Nhập mã, tên, MST, địa chỉ, địa bàn khách hàng, hoặc mã kho</label>
                <input id="pendingDeliveryAdviceCustomerFilter" class="k-textbox" style="text-align: center; margin-right: 13px;" onkeyup="pendingDeliveryAdviceCustomerFilter_KeyUp()" />
            </div>
        </text>);
    })
    .Scrollable(s => s.Height(Settings.PopupContentHeight))
    .DataSource(ds => ds.Ajax()
        .Read(read => read.Action("GetCustomers", "GoodsIssueAPIs", new { area = "Inventories" }).Data("onAdditionalGetCustomers"))
        .ServerOperation(false)//If this is TRUE: Apply filter to datasource will call Ajax to get new datasource result. If this is FALSE: filter will run on client
    )
    .Selectable()
)

@Html.Hidden("deliveryAdviceCustomerSearchText", "")

<script type="text/javascript">
    function onAdditionalGetCustomers(e) {
        return {
            locationID: window.parent.requireConfig.pageOptions.LocationID
        };
    }

    function pendingDeliveryAdviceCustomerFilter_KeyUp() {
        var pendingDeliveryAdviceCustomerFilter = $("#pendingDeliveryAdviceCustomerFilter").val(), gridDetails = $("#pendingDeliveryAdviceCustomerGrid").data("kendoGrid");

        if (pendingDeliveryAdviceCustomerFilter && pendingDeliveryAdviceCustomerFilter.length >= "@Settings.AutoCompleteMinLenght") {
            gridDetails.dataSource.filter({
                logic: "or",
                filters: [
                    { field: "CustomerCode", operator: "contains", value: pendingDeliveryAdviceCustomerFilter },
                    { field: "CustomerName", operator: "contains", value: pendingDeliveryAdviceCustomerFilter },
                    { field: "CustomerVATCode", operator: "contains", value: pendingDeliveryAdviceCustomerFilter },

                    { field: "ReceiverCode", operator: "contains", value: pendingDeliveryAdviceCustomerFilter },
                    { field: "ReceiverName", operator: "contains", value: pendingDeliveryAdviceCustomerFilter },
                    { field: "ReceiverVATCode", operator: "contains", value: pendingDeliveryAdviceCustomerFilter },

                    { field: "WarehouseCode", operator: "contains", value: pendingDeliveryAdviceCustomerFilter },

                    { field: "Addressee", operator: "contains", value: pendingDeliveryAdviceCustomerFilter },

                    { field: "ShippingAddress", operator: "contains", value: pendingDeliveryAdviceCustomerFilter }
                ]
            });


        } else {
            if (gridDetails.dataSource.filter() != undefined)
                gridDetails.dataSource.filter({});
        }
    }

    $("#pendingDeliveryAdviceCustomerGrid").dblclick(function (e) {
        okButton_Click();
    })
</script>