TotalSmartPortal/TotalPortal/Areas/Commons/ViewModels/CommodityPriceViewModel.cs
using System.Web.Mvc;
using System.Collections.Generic;

using TotalDTO.Commons;
using TotalPortal.Areas.Commons.ViewModels.Helpers;
using TotalPortal.ViewModels.Helpers;


namespace TotalPortal.Areas.Commons.ViewModels
{
    public class CommodityPriceViewModel : CommodityPriceDTO, ISimpleViewModel, IPriceCategoryDropDownViewModel
    {
        public IEnumerable<SelectListItem> PriceCategorySelectList { get; set; }
    }
}

TotalSmartPortal/TotalPortal/Areas/Commons/Controllers/CommodityPricesController.cs
using TotalModel.Models;

using TotalDTO.Commons;
using TotalCore.Services.Commons;

using TotalPortal.Controllers;
using TotalPortal.Areas.Commons.ViewModels;
using TotalPortal.Areas.Commons.Builders;


namespace TotalPortal.Areas.Commons.Controllers
{
    public class CommodityPricesController : GenericSimpleController<CommodityPrice, CommodityPriceDTO, CommodityPricePrimitiveDTO, CommodityPriceViewModel>
    {
        public CommodityPricesController(ICommodityPriceService commodityPriceService, ICommodityPriceSelectListBuilder commodityPriceViewModelSelectListBuilder)
            : base(commodityPriceService, commodityPriceViewModelSelectListBuilder)
        {
        }
    }
}


TotalSmartPortal/TotalPortal/Areas/Commons/Views/CommodityPrices/Create.cshtml
@model TotalPortal.Areas.Commons.ViewModels.CommodityPriceViewModel

@Html.Partial("_CommodityPrice")


TotalSmartPortal/TotalPortal/Areas/Commons/Views/CommodityPrices/Delete.cshtml
@Html.Partial("Edit")
@Html.Partial("~/Views/Helpers/Commons/_DeleteConfirm.cshtml")

TotalSmartPortal/TotalPortal/Areas/Commons/Views/CommodityPrices/Edit.cshtml
@model TotalPortal.Areas.Commons.ViewModels.CommodityPriceViewModel

@Html.Partial("_CommodityPrice")

TotalSmartPortal/TotalPortal/Areas/Commons/Views/CommodityPrices/Index.cshtml
@using TotalPortal.Configuration

@*@model TotalPortal.Areas.Commons.ViewModels.CommodityPriceViewModel*@

<div>
    @(Html.Kendo().Grid<TotalModel.Models.CommodityPriceIndex>()
        .Name("kendoGridIndex")
        .Columns(columns =>
        {
            columns.Bound(p => p.CommodityPriceID).DisplayNameTitle().Hidden();

            columns.Bound(p => p.CodePartA).Title("Mã SP").HtmlAttributes(new { @class = "grid-column-center" }).HeaderHtmlAttributes(new { @style = "text-align: center" }).Width(20).ClientTemplate("<a href='" + Url.RouteUrl("Default", new { controller = "Commons/CommodityPrices", action = "Edit" }) + "/#= CommodityPriceID #'>#=CodePartA#</a>");
            columns.Bound(p => p.CodePartB).Title("Mã bông").HtmlAttributes(new { @class = "grid-column-center" }).HeaderHtmlAttributes(new { @style = "text-align: center" }).Width(20);
            columns.Bound(p => p.CodePartC).Title("Nguyên liệu").HtmlAttributes(new { @class = "grid-column-center" }).HeaderHtmlAttributes(new { @style = "text-align: center" }).Width(20);
            columns.Bound(p => p.Weight).Title("Trọng lượng").Format(Settings.kfmWeight).HtmlAttributes(new { @class = "grid-number-column" }).HeaderHtmlAttributes(new { @style = "text-align: right" }).Filterable(false).Width(30);
            columns.Bound(p => p.ListedPrice).Title("ĐG chưa thuế").Format(Settings.kfmAmount).HtmlAttributes(new { @class = "grid-number-column" }).HeaderHtmlAttributes(new { @style = "text-align: right" }).Filterable(false).Width(30);
            columns.Bound(p => p.GrossPrice).Title("ĐG bao gồm VAT").Format(Settings.kfmAmount).HtmlAttributes(new { @class = "grid-number-column" }).HeaderHtmlAttributes(new { @style = "text-align: right" }).Filterable(false).Width(30);
            columns.Bound(p => p.Remarks).Title("Ghi chú").Width(180);
            
            columns.Template(model => null).HtmlAttributes(new { @class = "grid-column-center" }).Width(80)
                .ClientTemplate("<a class='k-button' style='padding-left:5px; min-width:28px; width:28px' href='" + Url.RouteUrl("Default", new { controller = "Commons/CommodityPrices", action = "Edit" }) + "/#= CommodityPriceID #'><span class='k-icon k-edit'></span></a> <a class='k-button' style='padding-left:0px; padding-right:0px; min-width:28px; width:28px' href='" + Url.RouteUrl("Default", new { controller = "Commons/CommodityPrices", action = "Delete" }) + "/#= CommodityPriceID #'><span class='k-icon k-delete'></span></a>");
        })
        .ToolBar(toolbar =>
        {
            toolbar.Template(@<text>
                <button type="button" class="k-button" onclick="location.href='@Url.Action("Create", "CommodityPrices")'"> <img src="~/Content/Images/New/2017/Tags/tag-24.png" /> Thêm đơn giá sản phẩm </button>
                <div class="toolbar" style="float: right;">
                    <label>Nhập kênh khách hàng, mã sản phẩm, mã bông, nguyên liệu hoặc ghi chú để tìm</label>
                    <input id="indexFilterText" class="k-textbox" style="text-align: center; " onkeyup="indexFilterText_KeyUp()" />
                </div>
            </text>);
        })
                .Pageable()
                .Groupable()
            //.Filterable()
                .Selectable()
                .Sortable()
                .Events(e =>
                {
                    e.DataBound("hightLightSelectedRow");
                })
                .DataSource(dataSource => dataSource
                    .Ajax()
                    .Group(group => group.AddDescending(p => p.PriceCategory))
                    .Read(read => read.Action("GetCommodityPriceIndexes", "CommodityPriceAPIs", new { area = "Commons" }))
                    //.Sort(sort =>
                    //    {
                    //        sort.Add(p => p.Name).Descending();
                    //    })
                    .PageSize(20)
                    .Model(model =>
                    {
                        model.Id(x => x.CommodityPriceID);
                        model.Field(m => m.CommodityPriceID).DefaultValue(0);
                    })
                    .ServerOperation(true)
                )
                .HtmlAttributes(new { @class = "grid-class" }))
</div>



<script type="text/javascript">
    function hightLightSelectedRow(e) {
        require(["kindexGrid"], function (kindexGrid) {
            var kindexGridInstance = new kindexGrid("kendoGridIndex");
            kindexGridInstance.setSelectedRow("CommodityPriceID", '@ViewBag.SelectedEntityID');
        });
    }

    function createWizard() {
        require(["kpopupWindow"], function (kpopupWindow) {
            var createWizardWindow = new kpopupWindow();
            createWizardWindow.openWindow($("#popupWindow"), "@Url.Action("CreateWizard", "CommodityPrices")", "Chọn khách hàng, chương trình khuyến mãi áp dụng cho khách hàng", "@Settings.PopupWidth", "@Settings.PopupHeightWithTab");
        });
    }


    function indexFilterText_KeyUp() {
        var indexFilterText = $("#indexFilterText").val(), gridDetails = $("#kendoGridIndex").data("kendoGrid");

        if (indexFilterText && indexFilterText.length >= "@Settings.AutoCompleteMinLenght") {
            gridDetails.dataSource.filter({
                logic: "or",
                filters: [
                    { field: "CodePartA", operator: "contains", value: indexFilterText },
                    { field: "CodePartB", operator: "contains", value: indexFilterText },
                    { field: "CodePartC", operator: "contains", value: indexFilterText },
                    { field: "CodePartABC", operator: "contains", value: indexFilterText },
                    { field: "Remarks", operator: "contains", value: indexFilterText }
                ]
            });


        } else {
            if (gridDetails.dataSource.filter() != undefined)
                gridDetails.dataSource.filter({});
        }
    }
</script>




TotalSmartPortal/TotalPortal/Areas/Commons/Views/CommodityPrices/_CommodityPrice.cshtml
@using TotalBase.Enums;
@using TotalPortal.Configuration

@model TotalPortal.Areas.Commons.ViewModels.CommodityPriceViewModel

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "MainForm" }))
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Helpers/Bases/_BaseSectionTop.cshtml")

    @Html.HiddenFor(model => model.CommodityPriceID)

    <div class="left-panel" style="height:30px;"></div>

    <div class="right-first-panel">

        @Html.Partial("~/Views/Shared/EditorTemplates/DropDowns/PriceCategory.cshtml")

        <div class="form-group">
            @Html.EditorFor(d => d.CodePartDTOA, new { SearchActionName = "GetCommodityCodePartA", CodePartLabel = @Model.GetDisplayName(m => m.CodePartDTOA) })
            <div class="div-validation-message">
                @Html.ValidationMessageFor(model => model.CodePartA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.EditorFor(d => d.CodePartDTOB, new { SearchActionName = "GetCommodityCodePartB", CodePartLabel = @Model.GetDisplayName(m => m.CodePartDTOB) })
            <div class="div-validation-message">
                @Html.ValidationMessageFor(model => model.CodePartB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.EditorFor(d => d.CodePartDTOC, new { SearchActionName = "GetCommodityCodePartC", CodePartLabel = @Model.GetDisplayName(m => m.CodePartDTOC) })
            <div class="div-validation-message">
                @Html.ValidationMessageFor(model => model.CodePartC, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.ListedPrice)
            <div class="div-input">
                @Html.Kendo().NumericTextBoxFor(model => model.ListedPrice).Format(Settings.kfmAmount).Decimals(0).HtmlAttributes(new { @class = "left-panel-input" })
            </div>
            <div class="div-validation-message">
                @Html.ValidationMessageFor(model => model.ListedPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GrossPrice)
            <div class="div-input">
                @Html.Kendo().NumericTextBoxFor(model => model.GrossPrice).Format(Settings.kfmAmount).Decimals(0).HtmlAttributes(new { @class = "left-panel-input" })
            </div>
            <div class="div-validation-message">
                @Html.ValidationMessageFor(model => model.GrossPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks)
            <div class="div-input">
                @Html.Kendo().MaskedTextBoxFor(model => model.Remarks).HtmlAttributes(new { @class = "left-panel-input" })
            </div>
            <div class="div-validation-message">
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="left-panel-input">
            @if (Model.Editable)
            {
                <button type="submit" class="k-button custom-button SubmitTypeOption-Closed" formaction="@Url.Action("Edit", "CommodityPrices")"> <img src="~/Content/Images/New/save-icon.png" /> Lưu giá bán sản phẩm </button>
            }
        </div>

        @Html.Partial("~/Views/Helpers/Bases/_BaseSubmit.cshtml")

    </div>
    <div class="left-panel" style="height:30px;"></div>
    <div class="left-panel" style="height:30px;"></div>
    <div class="right-panel">


    </div>
}
