TotalSmartPortal/TotalPortal/Areas/Sales/ViewModels/SalesReturnViewModel.cs
using System;
using System.Web.Mvc;
using System.Collections.Generic;

using TotalBase.Enums;
using TotalDTO.Sales;
using TotalPortal.Builders;
using TotalPortal.ViewModels.Helpers;
using TotalPortal.Areas.Commons.ViewModels.Helpers;

namespace TotalPortal.Areas.Sales.ViewModels
{
    public class SalesReturnViewModel : SalesReturnDTO, IViewDetailViewModel<SalesReturnDetailDTO>, IPreparedPersonDropDownViewModel, IApproverDropDownViewModel, IPaymentTermDropDownViewModel, IA02SimpleViewModel
    {
        public IEnumerable<SelectListItem> AspNetUserSelectList { get; set; }
        public IEnumerable<SelectListItem> PaymentTermSelectList { get; set; }
    }

}

TotalSmartPortal/TotalPortal/ViewModels/Helpers/PrintViewModel.cs
namespace TotalPortal.ViewModels.Helpers
{
    public class PrintViewModel
    {
        public int? Id { get; set; }
        public int? DetailID { get; set; }

        public int? FilterID { get; set; }

        public int LocationID { get; set; }

        public string ServerName { get { return "DATA-SERVER"; } }
        public string CatalogName { get { return "TotalSmartPortal"; } }

        public string ReportFolder { get { return "TotalSmartPortal"; } }
        public string ReportPath { get; set; }

        public int PrintOptionID { get; set; }
    }
}

TotalSmartPortal/TotalPortal/ViewModels/Helpers/VoidDetailViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

using TotalDTO.Commons;

namespace TotalPortal.ViewModels.Helpers
{
    public class VoidDetailViewModel
    {
        public int ID { get; set; }
        public int DetailID { get; set; }
        public bool InActivePartial { get; set; }

        public Nullable<int> VoidTypeID { get { return (this.VoidType != null ? this.VoidType.VoidTypeID : null); } }
        [UIHint("AutoCompletes/VoidType")]
        public VoidTypeBaseDTO VoidType { get; set; }

        public VoidDetailViewModel()
        {
            this.VoidType = new VoidTypeBaseDTO();
        }

    }
}

TotalSmartPortal/TotalPortal/Areas/Sales/Controllers/SalesReturnsController.cs
using System.Net;
using System.Web.Mvc;
using System.Text;

using AutoMapper;
using RequireJsNet;

using TotalBase.Enums;

using TotalModel.Models;

using TotalCore.Services.Sales;
using TotalCore.Repositories.Commons;

using TotalDTO.Sales;

using TotalPortal.Controllers;
using TotalPortal.Areas.Sales.ViewModels;
using TotalPortal.Areas.Sales.Builders;



namespace TotalPortal.Areas.Sales.Controllers
{
    public class SalesReturnsController : GenericViewDetailController<SalesReturn, SalesReturnDetail, SalesReturnViewDetail, SalesReturnDTO, SalesReturnPrimitiveDTO, SalesReturnDetailDTO, SalesReturnViewModel>
    {
        private readonly ICustomerRepository customerRepository;

        public SalesReturnsController(ISalesReturnService salesReturnService, ISalesReturnViewModelSelectListBuilder salesReturnViewModelSelectListBuilder, ICustomerRepository customerRepository)
            : base(salesReturnService, salesReturnViewModelSelectListBuilder, true)
        {
            this.customerRepository = customerRepository;
        }

        public override void AddRequireJsOptions()
        {
            base.AddRequireJsOptions();

            RequireJsOptions.Add("ApplyToSalesVersusReturns", (int)GlobalEnums.ApplyToSalesVersusReturns.ApplyToReturns, RequireJsOptionsScope.Page);

            StringBuilder commodityTypeIDList = new StringBuilder();
            commodityTypeIDList.Append((int)GlobalEnums.CommodityTypeID.Items);
            commodityTypeIDList.Append(","); commodityTypeIDList.Append((int)GlobalEnums.CommodityTypeID.Consumables);

            RequireJsOptions.Add("commodityTypeIDList", commodityTypeIDList.ToString(), RequireJsOptionsScope.Page);


            //USING THE SAME WarehouseTaskID WITH DeliveryAdvice. LATER, IF NEED NEW WarehouseTaskID FOR SalesReturn: JUST MODIFY HERE ONLY
            StringBuilder warehouseTaskIDList = new StringBuilder();
            warehouseTaskIDList.Append((int)GlobalEnums.WarehouseTaskID.DeliveryAdvice);

            ViewBag.WarehouseTaskID = (int)GlobalEnums.WarehouseTaskID.DeliveryAdvice;
            ViewBag.WarehouseTaskIDList = warehouseTaskIDList.ToString();
        }

        protected override bool GetShowDiscount(SalesReturnViewModel simpleViewModel)
        {
            return base.GetShowDiscount(simpleViewModel) || this.customerRepository.GetShowDiscount(simpleViewModel == null ? 0 : simpleViewModel.CustomerID);
        }

        protected override bool GetShowListedPrice(SalesReturnViewModel simpleViewModel)
        {
            return base.BaseService.GetShowListedPrice(simpleViewModel.PriceCategoryID);
        }

        protected override bool GetShowListedGrossPrice(SalesReturnViewModel simpleViewModel)
        {
            return base.BaseService.GetShowListedGrossPrice(simpleViewModel.PriceCategoryID);
        }

        public virtual ActionResult GetPendingGoodsIssueDetails()
        {
            this.AddRequireJsOptions();
            return View();
        }



    }

}

TotalSmartPortal/TotalPortal/Areas/Sales/Views/SalesReturns/Approve.cshtml
@Html.Partial("Edit")
@Html.Partial("~/Views/Helpers/Commons/_ApproveConfirmed.cshtml")

TotalSmartPortal/TotalPortal/Areas/Sales/Views/SalesReturns/Create.cshtml
@model TotalPortal.Areas.Sales.ViewModels.SalesReturnViewModel

@Html.Partial("_SalesReturn")

TotalSmartPortal/TotalPortal/Areas/Sales/Views/SalesReturns/CreateWizard.cshtml
@using TotalPortal.Configuration;

@{Layout = "~/Views/Shared/_LayoutPopup.cshtml";}

@model TotalPortal.Areas.Sales.ViewModels.SalesReturnViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.Partial("~/Views/Helpers/Bases/_BaseSectionTop.cshtml")

    @Html.Hidden("WarehouseTaskID", (int)@ViewBag.WarehouseTaskID);
    @Html.Hidden("WarehouseTaskIDList", (string)@ViewBag.WarehouseTaskIDList);
    
    @Html.HiddenFor(model => model.ShowDiscount);

    @Html.HiddenFor(model => model.HasGoodsIssue)
    @Html.HiddenFor(model => model.GoodsIssue.GoodsIssueID);
    @Html.HiddenFor(model => model.GoodsIssue.Reference);
    @Html.HiddenFor(model => model.GoodsIssue.EntryDate);
    @Html.HiddenFor(model => model.GoodsIssue.CustomerCode);
    @Html.HiddenFor(model => model.GoodsIssue.CustomerName);

    @Html.HiddenFor(model => model.PaymentTermID);

    @Html.HiddenFor(model => model.VATbyRow);
    @Html.HiddenFor(model => model.VATPercent);

    @Html.HiddenFor(model => model.TradePromotionID);
    @Html.HiddenFor(model => model.TradePromotionSpecs);//WHEN HasGoodsIssue WITHOUT GoodsIssueID => NOW: THE TradePromotionID WILL BE ONE OF THESE CURRENT/ ACTIVE TradePromotionID OF SELECTED CUSTOMER (GET CURRENT/ ACTIVE TradePromotionID FROM PROMOTION SETTING). LATER: WE SHOULD TO IMPLEMENT TradePromotionID->TO ALLOW USER CHANGE TradePromotionID MANUALLY (OR TO ALLOW TO SELECT IN-ACTIVE TradePromotionID, BACAUSE: AT THE TIME OF RETURN, THE SELLING PROMOTION WAS CLOSED)
    @Html.HiddenFor(model => model.TradeDiscountRate);//NOW: USER UNABLE TO CHANGE TradePromotionID (JUST SELECT ONE OF THESE CURRENT/ ACTIVE TradePromotionID OF SELECTED CUSTOMER) => WHEN HasGoodsIssue WITHOUT GoodsIssueID: => THE GoodsIssueDetails WITH TradePromotionID DIFFER FROM THE SELECTED TradePromotionID WILL BE NEVER LISTED IN GetPendingGoodsIssueDetails FOR SELECTION 
    
    @Html.HiddenFor(model => model.Salesperson.EmployeeID);
    @Html.HiddenFor(model => model.Salesperson.Name);

    @Html.HiddenFor(model => model.Promotion.PromotionID);
    @Html.HiddenFor(model => model.Promotion.Name);
    @Html.HiddenFor(model => model.Promotion.StartDate);
    @Html.HiddenFor(model => model.Promotion.EndDate);
    @Html.HiddenFor(model => model.Promotion.DiscountPercent);
    @Html.HiddenFor(model => model.Promotion.ControlFreeQuantity);
    @Html.HiddenFor(model => model.Promotion.ApplyToAllCustomers);
    @Html.HiddenFor(model => model.Promotion.ApplyToAllCommodities);
    @Html.HiddenFor(model => model.Promotion.Remarks);

    @Html.HiddenFor(model => model.Description);

    @Html.Partial("~/Views/Helpers/Commons/_SearchCustomer.cshtml")
    @Html.Partial("~/Areas/Sales/Views/SalesReturns/_GetGoodsIssue.cshtml")        


    <div class="background-bar" style="height: 45px;">
        <div class="popup-button-bar">
            <input id="submitCreateWizard" type="submit" formaction="@Url.Action("CreateWizard", "SalesReturns")" formtarget="_top" style="display:none" />

            <button type="button" class="k-button" onclick="handleOKEvent(true, true)"> <img src="~/Content/Images/Mains/Size24/Ok-1.png" /> Trả hàng phiếu xuất kho đang chọn </button>
            <button type="button" class="k-button" onclick="handleOKEvent(true, false)"> <img src="~/Content/Images/Mains/Size24/Accept-Total.png" /> Trả hàng của nhiều phiếu xuất kho </button>
            <button type="button" class="k-button" onclick="handleOKEvent(false, false)"> <img src="~/Content/Images/Mains/Size24/Accept-Total.png" /> Trả hàng không có phiếu xuất kho </button>
            <button type="button" class="k-button" onclick="window.parent.$('#myWindow').data('kendoWindow').close()"> <img src="~/Content/Images/Mains/Size24/Users-Exit-icon-24.png" /> Thoát </button>
        </div>
    </div>

}

<link href="@Url.Content("~/Content/CustomCss/GeneralPopup.css")" rel="stylesheet" type="text/css" />

<script type="text/javascript">

    function handleOKEvent(hasGoodsIssue, byGoodsIssueID) { //This javascript is now used only here. Later, if it is used somewhere else, it should be break into a standalone js file, and then just only add a link here
        
        $("#HasGoodsIssue").val(hasGoodsIssue);

        if ($("#Customer_CustomerID").val() === null || $("#Customer_CustomerID").val() === "")
            return false;
        
        if (hasGoodsIssue == true && byGoodsIssueID == true) {
            var selectedGrid = $("#salesReturnPendingGoodsIssueGrid").data("kendoGrid");
            var selectedDataItem = selectedGrid.dataItem(selectedGrid.select());
            if (selectedDataItem === undefined || selectedDataItem === null)
                return false;

            _setModelInput(selectedDataItem);
        }
        else {
            _setModelInput();
        }


        $("#submitCreateWizard").trigger("click");


        function _setModelInput(selectedDataItem) {
            
            $("#Salesperson_EmployeeID").val($("#Customer_SalespersonID").val()); //INIT DEFAULT Salesperson_EmployeeID, Salesperson_Name FROM Customer_SalespersonID, Customer_SalespersonName
            $("#Salesperson_Name").val($("#Customer_SalespersonName").val());

            $("#PaymentTermID").val($("#Customer_PaymentTermID").val());

            if (selectedDataItem != undefined) {
                $("#GoodsIssue_GoodsIssueID").val(selectedDataItem === undefined || selectedDataItem.GoodsIssueID === undefined ? null : selectedDataItem.GoodsIssueID);
                $("#GoodsIssue_Reference").val(selectedDataItem === undefined || selectedDataItem.GoodsIssueReference === undefined ? null : selectedDataItem.GoodsIssueReference);
                $("#GoodsIssue_EntryDate").val(selectedDataItem === undefined || selectedDataItem.GoodsIssueEntryDate === undefined ? null : kendo.toString(selectedDataItem.GoodsIssueEntryDate, Settings.DateTimeFormat));
                $("#GoodsIssue_CustomerCode").val(selectedDataItem === undefined || selectedDataItem.GoodsIssueID === undefined || selectedDataItem.CustomerCode === undefined ? null : selectedDataItem.CustomerCode);
                $("#GoodsIssue_CustomerName").val(selectedDataItem === undefined || selectedDataItem.GoodsIssueID === undefined || selectedDataItem.CustomerName === undefined ? null : selectedDataItem.CustomerName);

                $("#TradePromotionID").val(selectedDataItem === undefined || selectedDataItem.TradePromotionID === undefined ? null : selectedDataItem.TradePromotionID);
                $("#TradePromotionSpecs").val(selectedDataItem === undefined || selectedDataItem.TradePromotionSpecs === undefined ? null : selectedDataItem.TradePromotionSpecs);
                $("#TradeDiscountRate").val(selectedDataItem === undefined || selectedDataItem.TradeDiscountRate === undefined ? null : selectedDataItem.TradeDiscountRate);
                $("#VATPercent").val(selectedDataItem === undefined || selectedDataItem.VATPercent === undefined ? null : selectedDataItem.VATPercent);                                

                $("#ShippingAddress").val(selectedDataItem === undefined || selectedDataItem.ShippingAddress === undefined ? null : selectedDataItem.ShippingAddress);
                $("#Description").val(selectedDataItem === undefined || selectedDataItem.Description === undefined ? null : selectedDataItem.Description);
            }            
        }
    }

</script>


<style>
    #searchCustomer-div {
        border-radius: 0px;
        border-top-style: none;
    }

    #gridPromotion { /*Don't allow to select any specific promotion. As the same as the SalesOrder and DeliveryAdvice: NO specific promotion MEANS: ALL PROMOTIONS EFFECTED*/
        display: none;
    }
</style>

TotalSmartPortal/TotalPortal/Areas/Sales/Views/SalesReturns/Delete.cshtml
@Html.Partial("Edit")
@Html.Partial("~/Views/Helpers/Commons/_DeleteConfirm.cshtml")

TotalSmartPortal/TotalPortal/Areas/Sales/Views/SalesReturns/Edit.cshtml
@model TotalPortal.Areas.Sales.ViewModels.SalesReturnViewModel

@Html.Partial("_SalesReturn")

TotalSmartPortal/TotalPortal/Areas/Sales/Views/SalesReturns/Index.cshtml
@using TotalPortal.Configuration

<div id="popupWindow"></div>

<div>
    @(Html.Kendo().Grid<TotalModel.Models.SalesReturnIndex>()
            .Name("kendoGridIndex")
            .Columns(columns =>
            {
                columns.Bound(p => p.SalesReturnID).DisplayNameTitle().Hidden();                
                columns.Bound(p => p.EntryDate).Title("Ngày").Format("{0:dd/MM/yyyy}").Width(10).Filterable(false);

                columns.Bound(p => p.Reference).Title("#").Width(10).Filterable(false).ClientTemplate("<a href='" + Url.RouteUrl("Default", new { controller = "Sales/SalesReturns", action = "Edit" }) + "/#= SalesReturnID #'>#=Reference#</a>");
                columns.Bound(p => p.GoodsIssueReferences).Title("PXK").Width(100).Filterable(false);
                columns.Bound(p => p.CustomerName).Title("Khách hàng").Width(200);
                columns.Bound(p => p.ReceiverDescription).Title("Nhận hàng").Width(160);
                columns.Bound(p => p.Description).Title("Diễn giải").Width(130);
                

                columns.Bound(p => p.GrandTotalQuantity).Title("Trả hàng").Format(Settings.kfmQuantity).HtmlAttributes(new { @class = "grid-number-column" }).HeaderHtmlAttributes(new { @style = "text-align: right"}).Filterable(false).Width(20).ClientFooterTemplate("#= kendo.format('" + Settings.kfmQuantity + "', sum) #").FooterHtmlAttributes(new { @class = "grid-number-column" });
                columns.Bound(p => p.GrandTotalQuantityReceived).Title("Nhập kho").Format(Settings.kfmQuantity).HtmlAttributes(new { @class = "grid-number-column" }).HeaderHtmlAttributes(new { @style = "text-align: right"}).Filterable(false).Width(20).ClientFooterTemplate("#= kendo.format('" + Settings.kfmQuantity + "', sum) #").FooterHtmlAttributes(new { @class = "grid-number-column" });
                columns.Bound(p => p.TotalListedGrossAmount).Title("Thành tiền").Format(Settings.kfmAmount).HtmlAttributes(new { @class = "grid-number-column" }).HeaderHtmlAttributes(new { @style = "text-align: right"}).Filterable(false).Width(50).ClientFooterTemplate("#= kendo.format('" + Settings.kfmAmount + "', sum) #").FooterHtmlAttributes(new { @class = "grid-number-column" }).Hidden(@ViewBag.ShowDiscount ? true : false);
                columns.Bound(p => p.TotalGrossAmount).Title("Thành tiền").Format(Settings.kfmAmount).HtmlAttributes(new { @class = "grid-number-column" }).HeaderHtmlAttributes(new { @style = "text-align: right"}).Filterable(false).Width(50).ClientFooterTemplate("#= kendo.format('" + Settings.kfmAmount + "', sum) #").FooterHtmlAttributes(new { @class = "grid-number-column" }).Hidden(@ViewBag.ShowDiscount ? false : true);

                columns.Template(model => null).HtmlAttributes(new { @class = "grid-column-center" }).Width(92)
                    .ClientTemplate("<a class='k-button' style='padding-left:5px; min-width:28px; width:28px' href='" + Url.RouteUrl("Default", new { controller = "Sales/SalesReturns", action = "Void" }) + "/#= SalesReturnID #'><span class='k-icon k-edit'></span></a> <a class='k-button' style='padding-left:0px; padding-right:0px; min-width:28px; width:28px' href='" + Url.RouteUrl("Default", new { controller = "Sales/SalesReturns", action = "Delete" }) + "/#= SalesReturnID #'><span class='k-icon k-delete'></span></a>");                    
            })
            .ToolBar(toolbar =>
            {
                toolbar.Template(@<text> 
                    <button type="button" class="k-button" onclick="createWizard()"> <img src="~/Content/Images/Mains/Size24/folder-documents-icon-24.png" /> Lập phiếu trả hàng </button> 
                    <div class="toolbar" style="float: right;">
                        <label>Nhập số phiếu trả hàng, phiếu xuất kho hoặc tên khách hàng để tìm</label>
                        <input id="indexFilterText" class="k-textbox" style="text-align: center; " onkeyup="indexFilterText_KeyUp()" />
                    </div>
                </text>);
            })
            .Pageable()
            .Groupable(g => g.Messages(messages => messages.Empty("Phân nhóm dữ liệu: Kéo và thả tiêu đề một hoặc nhiều cột dữ liệu ngay bên dưới vào đây để phân nhóm hiển thị theo phân cấp của các cột dữ liệu")))            
            .Selectable()
            .Sortable()
            .Events(e =>
            {
                e.DataBound("hightLightSelectedRow");
            })
            .DataSource(dataSource => dataSource
                .Ajax()
                .Read(read => read.Action("GetSalesReturnIndexes", "SalesReturnAPIs", new { area = "Sales" }))
                .Sort(sort =>
                    {
                        sort.Add(p => p.EntryDate).Descending();
                        sort.Add(p => p.SalesReturnID).Descending();
                    })
                .PageSize(20)
                .Model(model =>
                {
                    model.Id(x => x.SalesReturnID);
                    model.Field(m => m.SalesReturnID).DefaultValue(0);
                })
                .ServerOperation(true)
                .Aggregates(a => a.Add(x => x.GrandTotalQuantity).Sum())
                .Aggregates(a => a.Add(x => x.GrandTotalQuantityReceived).Sum())
                .Aggregates(a => a.Add(x => x.TotalListedGrossAmount).Sum())
                .Aggregates(a => a.Add(x => x.TotalGrossAmount).Sum())
                )
            .HtmlAttributes(new { @class = "grid-class" }))
</div>



<script type="text/javascript">
    function hightLightSelectedRow(e) {
        require(["kindexGrid"], function (kindexGrid) {
            var kindexGridInstance = new kindexGrid("kendoGridIndex");
            kindexGridInstance.setSelectedRow("SalesReturnID", '@ViewBag.SelectedEntityID');
        });
    }

    function createWizard() {
        require(["kpopupWindow"], function (kpopupWindow) {
            var createWizardWindow = new kpopupWindow();
            createWizardWindow.openWindow($("#popupWindow"), "@Url.Action("CreateWizard", "SalesReturns")", "Chọn khách hàng, phiếu xuất kho trả hàng", "@Settings.PopupWidth", 594);
        });
    }


    decoratingKindex = function (idx, elem) {

        if (elem.Approved == null || elem.Approved == false) {
            $('tr[data-uid="' + elem.uid + '"]').addClass("NotApproved");
        }
    }







    function indexFilterText_KeyUp() {
        var indexFilterText = $("#indexFilterText").val(), gridDetails = $("#kendoGridIndex").data("kendoGrid");

        if (indexFilterText && indexFilterText.length >= "@Settings.AutoCompleteMinLenght") {
            gridDetails.dataSource.filter({
                logic: "or",
                filters: [
                    { field: "Reference", operator: "contains", value: indexFilterText },
                    { field: "GoodsIssueReferences", operator: "contains", value: indexFilterText },

                    { field: "CustomerName", operator: "contains", value: indexFilterText }
                ]
            });


        } else {
            if (gridDetails.dataSource.filter() != undefined)
                gridDetails.dataSource.filter({});
        }
    }

</script>




TotalSmartPortal/TotalPortal/Areas/Sales/Views/SalesReturns/Open.cshtml
@model TotalPortal.Areas.Sales.ViewModels.SalesReturnViewModel

@Html.Partial("_SalesReturn")

TotalSmartPortal/TotalPortal/Areas/Sales/Views/SalesReturns/Print.cshtml
@using MvcReportViewer;
@model TotalPortal.ViewModels.Helpers.PrintViewModel

@Html.MvcReportViewerFluent("/TotalSmartPortal/SalesReturnSumUp").ReportParameters(new { SalesReturnID = @Model.Id, CurrentHost = HttpContext.Current.Request.Url.Host }).Attributes(new { Height = 1100, Width = 1150, style = "border: none" }).ControlSettings(new ControlSettings() { ShowParameterPrompts = false })

TotalSmartPortal/TotalPortal/Areas/Sales/Views/SalesReturns/Void.cshtml
@Html.Partial("Edit")
@Html.Partial("~/Views/Helpers/Commons/_VoidConfirmed.cshtml")

TotalSmartPortal/TotalPortal/Areas/Sales/Views/SalesReturns/VoidDetail.cshtml
@using TotalPortal.Configuration;

@{Layout = "~/Views/Shared/_LayoutPopup.cshtml";}

@model TotalPortal.Areas.Sales.ViewModels.SalesReturnViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.Hidden("Id", @Model.SalesReturnID);

    if (Model.ViewDetails.Count > 0)
    {
        @Html.Hidden("DetailId", @Model.ViewDetails[0].SalesReturnDetailID);
        @Html.Hidden("InActivePartial", @Model.ViewDetails[0].InActivePartial);
        <div class="left-panel">
            <div style="padding: 16px;"> <img src="~/Content/Images/Mains/@(@Model.ViewDetails[0].InActivePartial ? "iSync-icon64.png" : "blue-cross-icon64.png")" title="Hủy/ phục hồi một phần đơn hàng" />  </div>
        </div>
        <div class="right-panel" style="padding-right:17px;">
            <div class=" form-group">
                @Html.LabelFor(model => model.ViewDetails[0].CommodityName)
                <div class="div-input">
                    @Html.Kendo().MaskedTextBoxFor(model => model.ViewDetails[0].CommodityName).HtmlAttributes(new { @class = "left-panel-input", @readonly = "readonly" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ViewDetails[0].Quantity)
                <div class="div-input">
                    @Html.Kendo().MaskedTextBoxFor(model => model.ViewDetails[0].Quantity).HtmlAttributes(new { @class = "left-panel-input", @readonly = "readonly" })
                </div>
            </div>

            <div class="form-group">
                @Html.EditorFor(d => d.VoidType)
            </div>
            
            
        </div>
        <div class="background-bar">
            <div class="popup-button-bar">
                <button type="submit" class="k-button"> <img src="~/Content/Images/Mains/@(@Model.ViewDetails[0].InActivePartial ? "iSync-icon32.png" : "blue-cross-icon32.png")" alt="" /> Xác nhận @(@Model.ViewDetails[0].InActivePartial ? "phục hồi" : "hủy") mặt hàng này </button>
                <button type="button" class="k-button" onclick="window.parent.$('#myWindow').data('kendoWindow').close()"> <img src="~/Content/Images/Mains/Users-Exit-icon.png" alt="" /> Thoát </button>                
            </div>
        </div>
    }
}
@Html.Partial("~/Views/Helpers/Bases/_BaseSubmit.cshtml")



<link href="@Url.Content("~/Content/CustomCss/GeneralPopup.css")" rel="stylesheet" type="text/css" />

<script type="text/javascript">

    function cancelButton_Click() {
        window.parent.$("#myWindow").data("kendoWindow").close();
    }


</script>

<style>
    .left-panel-input {
        width: 100%;
    }
</style>

TotalSmartPortal/TotalPortal/Areas/Sales/Views/SalesReturns/VoidDetailSuccess.cshtml
@model TotalPortal.ViewModels.Helpers.VoidDetailViewModel

@{Layout = "~/Views/Shared/_LayoutPopup.cshtml";}

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.DetailID)
    @Html.HiddenFor(model => model.InActivePartial)
    @Html.HiddenFor(model => model.VoidType.Name)
}

<script type="text/javascript">
    $(document).ready(function () {
        var kenGrid = window.parent.$("#kendoGridDetails").data("kendoGrid");
        var data = kenGrid.dataSource.data();

        $.each(data, function (i, row) {
            if (row.SalesReturnDetailID == $("#DetailID").val()) {
                
                //This will raise kendo grid DataBound event (to style grid row). Now: we set only one field to raise DataBound event one time only. (The control will raise event per each row.set command)
                row.set("VoidTypeName", ($("#InActivePartial").val() == 'True' ? $("#VoidType_Name").val() : ''));
                //Important note: this Success response does not set all necessary fields for the model, ex: InActivePartial, VoidTypeID, ...
                //So: Never submit model to save to database when in void mode

                //Note: Don't remove this code for later refer as an example of how to add/  remove style to current gird.
                //if ($("#InActivePartial").val() == 'True' && window.parent.$('tr[data-uid="' + row.uid + '"]').hasClass("isBonus") == false)
                //    window.parent.$('tr[data-uid="' + row.uid + '"]').addClass("isBonus");
                //if ($("#InActivePartial").val() == 'False' && window.parent.$('tr[data-uid="' + row.uid + '"]').hasClass("isBonus") == true)
                //    window.parent.$('tr[data-uid="' + row.uid + '"]').removeClass("isBonus");

                return false;
            }
        });

        window.parent.$("#myWindow").data("kendoWindow").close();
    });
</script>